### ISSUE TITLE
Move Repo to a Standalone ( non-fork ) Repository

### ISSUE THREAD

**Issue by zicklag** [riotkit-org/docker-taiga#14]
To increase discoverability on GitHub I think it would be good to migrate the repository to a standalone repository so that it will pop up in GitHub searches.

You have to contact GitHub support to have them migrate the repo: https://help.github.com/en/articles/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork.

**Comment by blackandred** [comment]
Thank you Zicklag, I will contact github support to migrate the repo. Good
to know! :slightly_smiling_face:

**Comment by blackandred** [comment]
Ticket created.

**Comment by blackandred** [comment]
Done :slightly_smiling_face:
