### ISSUE TITLE
Do we need to have SSL support in NGINX?

### ISSUE THREAD

**Issue by blackandred** [riotkit-org/docker-taiga#16]
Hi,

I personally don't think that the docker container should use SSL certificate by it's own on the internal webserver. The certificate should be managed by a gateway webserver in the docker network. So I do not see a reason to maintain such functionality - I don't think anybody on production would use such functionality.

What do you think?
The SSL support in NGINX is coming there from forked repository, it wasnt even fully tested.

**Comment by zicklag** [comment]
I know that I personally and in my business don't ever copy SSL certs into containers because I use a Traefik reverse proxy for everything. I don't see much of a reason to continue to maintain that support unless somebody had asked for it and we decided that the need was worth the maintenance cost.
