### ISSUE TITLE
Email notification not working

### ISSUE THREAD

**Issue by suren2306** [riotkit-org/docker-taiga#29]
I have updated the SMTP server details in `.env` file, but I am not getting any email notification (when a task is assigned, task status change, etc). I have tested the SMTP details by triggering a test mail using the command,
`python manage.py sendtestemail mymail@mydomain.com`
I got the test mail in my inbox, whereas I am not getting any other email from Taiga. I manually triggered the email using `python manage.py send_notifications`, and got all my notification emails.

Below is my SMTP configuration in `.env` file,

```
# To use an external SMTP for emails, fill in these values:
TAIGA_ENABLE_EMAIL=True
TAIGA_EMAIL_FROM=taiga@mydomain.com
TAIGA_EMAIL_USE_TLS=True
TAIGA_EMAIL_HOST=my-smtp-server
TAIGA_EMAIL_PORT=587
TAIGA_EMAIL_USER=XXXXXXXXXXXXXXXXXXXXXXXXXX
TAIGA_EMAIL_PASS=XXXXXXXXXXXXXXXXXXXXXXXXXXX

# events
#TAIGA_ENABLE_EVENTS=false
#TAIGA_EVENTS_HOST=events
#TAIGA_BROKER_URL=amqp://guest:guest@rabbit:5672
#TAIGA_REDIS_URL=redis://redis:6379/0
```

**Comment by blackandred** [comment]
> I manually triggered the email using python manage.py send_notifications,
and got all my notification emails.

So, do you suggest that we do not trigger a cronjob? That looks like a bug
or lack of a feature in the container.
Feel free to send a PR if you are able, if not then you will need to wait
when I will have a few free hours to get it working :)

**Comment by emeraldhieu** [comment]
I got the same issue. Email is not sent though it works with https://www.gmass.co/smtp-test.
```
TAIGA_ENABLE_EMAIL=True
TAIGA_EMAIL_FROM=<hidden>
TAIGA_EMAIL_USE_TLS=True
TAIGA_EMAIL_HOST=smtp.mailgun.org
TAIGA_EMAIL_PORT=587
TAIGA_EMAIL_USER=<hidden>
TAIGA_EMAIL_PASS=<hidden>
```

**Comment by blackandred** [comment]
Resolved. Please have a look at https://github.com/riotkit-org/docker-taiga/releases/tag/1.2-RC1 , test it, give feedback. Closing the issue now, I could reopen if the issue will be still present.
