### ISSUE TITLE
chown: cannot access '/var/run/nginx.pid': No such file or directory

### ISSUE THREAD

**Issue by unixfox** [riotkit-org/docker-taiga#30]
When `docker-compose restart taiga` I get this error that only occurs when taiga restart:
```
taiga_1     |  >> Setting user id and group id
taiga_1     | usermod: no changes
taiga_1     |  >> Correcting permissions
taiga_1     | chown: cannot access '/var/run/nginx.pid': No such file or directory
```

A `docker-compose down` is then required to force the container to rebuild and thus temporary fixing the error.

**Comment by blackandred** [comment]
Resolved. Please have a look at https://github.com/riotkit-org/docker-taiga/releases/tag/1.2-RC1 , test it, give feedback. Closing the issue now, I could reopen if the issue will be still present.
