### ISSUE TITLE
Migrations do not finish

### ISSUE THREAD

**Issue by Pwarde** [riotkit-org/docker-taiga#45]
On rkd :start, the db migrations do not finish.
This results in missing db fields and admin account is not created.

Running the migrations from within the container and loading the initial user fixture resolves the issue but should be properly done by the script.

**Comment by blackandred** [comment]
Hi,

rkd :start invokes a docker-compose, I don't think there could be any difference.

Could you please add any logs?

**Comment by Pwarde** [comment]
Unfortunately I did not save the logs and am happy that I got everything running.
I might do a new deployment later to generate some log files.

**Comment by blackandred** [comment]
I see no activitiy there, closing for now.
