### ISSUE TITLE
Update with latest releases of Taiga 4.2.13

### ISSUE THREAD

**Issue by Leopere** [riotkit-org/docker-taiga#8]
Not sure if you're planning on CI/CD automation for building with the latest releases from Taiga upstream but we're a number of releases behind.  https://github.com/taigaio/taiga-front/releases

**Comment by zicklag** [comment]
@blackandred Has said that he will be getting CI setup. If you need the latest version now it is super easy to build the container for a different version of Taiga using the build arguments:

```bash
$ docker build -t taiga --build-arg TAIGA_BACK_VERSION=4.2.12 --build-arg TAIGA_FRONT_VERSION=4.2.12-stable .
```

**Comment by blackandred** [comment]
Hi,

I have just today created an automation that I need only to connect.
At first I'm connecting it to a new container project (Django Wiki) as its easier, does not need to refactor.

The automation iterates over recent X tags from github releases and executes build & push for them.

Automation:
https://github.com/riotkit-org/ci-utils/blob/master/bin/for-each-github-release

And usage:
https://github.com/riotkit-org/docker-django-wiki/blob/master/Makefile#L40

I will implement it soon to the Taiga container.

**Comment by Leopere** [comment]
I'm not in a huge rush but it would be good to see some method for keeping up with the latest release this plus coupled with #6 would make a full test suite possible.

**Comment by blackandred** [comment]
Sure, it will work. I made similar automations for other applications such as PhpBB or DokuWiki.
There is a PR with partial functionality, it's work in progress. I will create a travis environment soon. At now I have a work in other area - I have to create my speech for the Solidarity with Rojava demonstration :blush:

**Comment by blackandred** [comment]
Closing as a CI was set up. Feel free to reopen if needed.

**Comment by Leopere** [comment]
One last question, will the latest supported Taiga release be tagged Latest in the docker images?

**Comment by blackandred** [comment]
Nope. I didn't implement latest. I don't like the latest tag, because it
could mean everything - it's a last push to repository. Maybe there could
be considered something like "latest-stable", which would point always to
the recent release.
